"""add index to owner_id

Revision ID: e391d156decb
Revises: fb17ef505bce
Create Date: 2026-05-02 17:59:45.622676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e391d156decb'
down_revision = 'fb17ef505bce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_devices_owner_id'), 'devices', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_owner_id'), table_name='devices')
    # ### end Alembic commands ###
